### ISSUE TITLE
css loader

### ISSUE THREAD

**Issue by Sainthilaire-thomas** [pinussilvestrus/postit-js#172]
Hello,
thank you for your help because I think it is a beginner mistake: 

I have created a directory and installed postit-js-core: $ npm install postit-js-core --save
then I copied the example files in a subdirectory example and 
followed ;
$ cd  example
$ npm install
$ npm run dev
I have installed css-loader and style-loader in the main and subdirectoriy (in case of)

but I keep having this error:

ERROR in ../node_modules/postit-js-core/assets/postit-js.css (./node_modules/css-loader/dist/cjs.js!../node_modules/postit-js-core/assets/postit-js.css) 
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../node_modules/diagram-js/assets/diagram-js.css' in 'C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\node_modules\postit-js-core\assets'
    at finishWithoutResolve (C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\Resolver.js:309:18)
    at C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\Resolver.js:386:15
    at C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\Resolver.js:435:5
    at eval (eval at create (C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\Resolver.js:435:5
    at eval (eval at create (C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:87:43
    at C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\Resolver.js:435:5
    at eval (eval at create (C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\thoma\OneDrive\SONEAR 2023\postit-js-scratch\example\node_modules\enhanced-resolve\lib\Resolver.js:435:5
 @ ../node_modules/postit-js-core/assets/postit-js.css 8:6-117 22:17-24 26:0-87 26:0-87 27:22-29 27:33-47 27:50-64
 @ ./app/app.js 3:0-45

webpack 5.78.0 compiled with 1 error in 1905 ms

**Comment by Sainthilaire-thomas** [comment]
I have solved my issue, I needed to copy all the files in the main directory,
sorry for the interruption, have a nice easter and bravo for the postit-js, very well done !
I keep learning at 62 thanks to you

**Comment by pinussilvestrus** [comment]
> I have solved my issue, I needed to copy all the files in the main directory, sorry for the interruption, have a nice easter and bravo for the postit-js, very well done ! I keep learning at 62 thanks to you

Nice to hear that, thanks for the feedback! ❤️
