### ISSUE TITLE
Grid Align Feature

### ISSUE THREAD

**Issue by xanpj** [pinussilvestrus/postit-js#25]
**Grid Align Feature**

This will make elements in a group align into a grid and resize the group element to wrap around them.
How should this feature be activated? 

- Key command
- Dedicated button in pallete
- Button appearing in floating menu or top right menu when multiple elements are selected.

<img width="1280" alt="Screen Shot 2020-06-10 at 8 09 06 PM" src="https://user-images.githubusercontent.com/3321506/84302853-45836e80-ab56-11ea-9b22-74088e560220.png">
<img width="1280" alt="Screen Shot 2020-06-10 at 8 08 50 PM" src="https://user-images.githubusercontent.com/3321506/84302854-461c0500-ab56-11ea-80dd-5bddd484e7e6.png">

**Comment by pinussilvestrus** [comment]
We could simply use [the GridSnapping feature of diagram-js](https://github.com/bpmn-io/diagram-js/tree/develop/lib/features/grid-snapping) for this.

**Comment by xanpj** [comment]
The Grid Snapping feature is really nice!  Maybe in one of the readme's in any of the library repos 
we should list all available extensions.

Yet, what I have a mind is a button that will grid snap all elements in a selection AND snap the box around it. Core or not?

**Comment by pinussilvestrus** [comment]
Sounds like another cool extension to me 🚀🍾

**Comment by xanpj** [comment]
I have uploaded the feature as a module in https://github.com/xanpj/postit-js-extensions

**Comment by pinussilvestrus** [comment]
Cool! Thanks a lot 👍 

I just added an extension section to the readme (https://github.com/pinussilvestrus/postit-js/commit/a847bbff46dada573a873d04fc3aba150f954a0e) and tweeted about it: https://twitter.com/lutki95/status/1272521690430550018

🚀
