### ISSUE TITLE
How to set businessObject attributes at creation time

### ISSUE THREAD

**Issue by xanpj** [pinussilvestrus/postit-js#32]
Hi @pinussilvestrus 
this time it's a question from my side.

I understand that attributes set in the xml are loaded as attributes (`$attrs`) inside the `businessObject` of an element. From then on they are meant to be read only.

What would be the best way to set the `$attrs` manually at creation time? (i.e. here)
```
const shape = _elementFactory.createShape({
      type: type,
      ...options,
  });
```
I am thinking of a scenario where I undo the history in the panel and need to recreate some elements. However, I want to set them as `$attrs` instead of object properties so that elements stay consistent with the way they'd look if they'd be loaded fresh from an xml.

I hope that makes sense.

**Comment by pinussilvestrus** [comment]
Attributes only go inside `$attrs` when they are not properly defined in the [moddle descriptors](https://github.com/pinussilvestrus/postit-js/blob/master/lib/moddle/resources/postit.json). If they are defined, they should directly be inside the `businessObject`. Therefore the `$attrs` element is not the standard way to do it. 

Why it is needed? Are you using properties that are not defined in the postit-js moddle descriptors?

**Comment by xanpj** [comment]
> Attributes only go inside `$attrs` when they are not properly defined in the [moddle descriptors](https://github.com/pinussilvestrus/postit-js/blob/master/lib/moddle/resources/postit.json). If they are defined, they should directly be inside the `businessObject`. Therefore the `$attrs` element is not the standard way to do it.
> 
> Why it is needed? Are you using properties that are not defined in the postit-js moddle descriptors?

That makes sense! Yes, I did not define the additional properties I use for the features accessible in the properties panel (hidden image, unkeyed image ...). Thanks.
