### ISSUE TITLE
Netlify experiments demo

### ISSUE THREAD

**Issue by xanpj** [pinussilvestrus/postit-js#35]
Hi, how about netlifying the extension-experiments in the `experiments `branch instead of the `live` branch. The v2 extensions require a modified `lib` and `less` so they don't work on the `master` branch.

We could probably also remove extension-experiments/ in the `master` branch.

**Comment by pinussilvestrus** [comment]
The https://postit-js-experiments.netlify.app/ demo is exactly doing this. It's deploying the experiments branch and the `extension-experiments` example.

**Comment by pinussilvestrus** [comment]
![image](https://user-images.githubusercontent.com/9433996/89376204-a612d000-d6ef-11ea-8c02-902cf8bd4600.png)
