### ISSUE TITLE
postinstall / .npmignore issue

### ISSUE THREAD

**Issue by qloikp** [pinussilvestrus/postit-js#36]
Hej,

using `npm install` results in an FileNotFound error when running the `postinstall` script, since it can't find the directory ./example/ since it is an entry within `.npmignore`.

I'm not sure, what the expected behaviour would be, hence no PR. I tested it in my fork with both workarounds - seemingly working fine.

Cheers, qloikp

**Comment by pinussilvestrus** [comment]
Thanks for the hint. I simply added the examples to the package, should be fine though.

**Comment by pinussilvestrus** [comment]
Thanks! I removed the postinstall script, no need to handle the examples this way. Should work now with version `v0.6.2`.
