### ISSUE TITLE
Problem using a website.

### ISSUE THREAD

**Issue by eiadmohamed** [pinussilvestrus/postit-js#69]
Hey guyz

iam trying to access this website " https://datdrop.com/ " most of times it doesn't work , and if it works it works for like 5 minutes then it stops , tried dns change , most of solutions it didn't work..  it works fine on iphone only but pc , android nope..

![Screenshot_42](https://user-images.githubusercontent.com/84224211/118353497-c74dfa00-b566-11eb-9a64-87c777763842.png)

my internet operator said site respone time is high  , and site owners said servers are working fine in egypt.

![Screenshot_43](https://user-images.githubusercontent.com/84224211/118353519-e8164f80-b566-11eb-9dee-0042fcbb38af.png)

**Comment by pinussilvestrus** [comment]
Doesn't relate to this repo, so I'm deleting it.
