### ISSUE TITLE
What script do I run to keep it running continuously on the server?

### ISSUE THREAD

**Issue by jordanurbs** [pinussilvestrus/postit-js#89]
Sorry for the newb Node question but whether I use npm run dev, npm run prod, npm build, etc, they all will terminate when I end my SSH session with my server. How do I keep it running?

**Comment by pinussilvestrus** [comment]
I don't know whether this is something really related to this project. When I connect to servers, I usually use process managers like [`pm2`](https://github.com/Unitech/pm2) to ensure my node tasks run after I logged out.

**Comment by pinussilvestrus** [comment]
Do you have any idea how this project can support outside of using a proper process manager?

**Comment by jordanurbs** [comment]
Got it, thank you. I can work with pm2.
