### ISSUE TITLE
npm package is missing resources folder for moddle

### ISSUE THREAD

**Issue by Meleeman01** [pinussilvestrus/postit-js#95]
https://github.com/pinussilvestrus/postit-js/tree/main/lib/moddle

without those files in the resources it can't build with webpack/laravel-mix

**Comment by pinussilvestrus** [comment]
Thanks for reporting, the moddle descriptors were indeed missed. That should be fixed with [`v1.0.1`](https://github.com/pinussilvestrus/postit-js/tree/v1.0.1), can you maybe double check?
